name: Build cv

on:
  push:
    branches:
      - main
  pull_request:
  registry_package:

jobs:
  build-template:
    name: Build cv
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build pdf
        run: latexmk -pdflua ./cv.tex

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./cv.pdf
          overwrite: true

      - name: Upload log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cv.log
          path: ./cv.log
          
      - name: move
        run: mkdir -p github_artifacts && mv ./cv.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./github_artifacts
          overwrite: true
  deploy:
    needs: [build-template]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
          merge-multiple: true
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
